import { Button, VerticalBox } from "std-widgets.slint";

// Explicit positioning
export component AppWindow inherits Window {
    preferred-width: 200px;
    preferred-height: 200px;
    Rectangle {
        x: 100px;
        y: 70px;
        width: parent.width - self.x;
        height: parent.height - self.y;
        background: blue;
        Rectangle {
            x: 10px;
            y: 5px;
            width: 50px;
            height: 30px;
            background: green;
        }
    }
}
